FROM python:2

WORKDIR /src/

COPY requirements.txt /src/

COPY model_design_docker.py /src/

COPY model_design.py /src/

RUN pip install -r /src/requirements.txt

CMD ["python", "/src/model_design_docker.py"]
